Avito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('bboard.urls', namespace='')),
    path('social/', include('social_django.urls', namespace = 'social')),
]

if settings.DEBUG:
	urlpatterns.append(path('static/<path:path>', 
						never_cache(serve)))
	urlpatterns += static(settings.MEDIA_URL,
							document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path

from .views import bbs
from .views import BbDetailView
from .views import comments

urlpatterns = [
	path('bbs/<int:pk>/comments/', comments),
	path('bbs/<int:pk>/', BbDetailView.as_view()),
	path('bbs/', bbs),
]

bboard/urls.py
from django.urls import path

from .views import index
from .views import other_page
from .views import BBLoginView
from .views import BBLogoutView
from .views import profile
from .views import ChengeUserInfoView
from .views import BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView
from .views import user_activate
from .views import DeleteUserView
from .views import by_rubric
from .views import detail
from .views import profile_bb_detail
from .views import profile_bb_add, profile_bb_change, profile_bb_delete

app_name='bboard' #Название приложения из пространства имён для сопоставления URL-адресов.
urlpatterns = [
	path('accounts/register/activate/<str:sign>', user_activate,
	 	name = 'register_activate'),
	path('accounts/register/done/', RegisterDoneView.as_view(), 
		name = 'register_done'),
	path('accounts/register/', RegisterUserView.as_view(), 
		name = 'register'),
	path('accounts/password/change/', BBPasswordChangeView.as_view(), 
		name = 'password_change'),
	path('accounts/profile/delete/', DeleteUserView.as_view(),
		name = 'profile_delete'),
	path('accounts/profile/change/', ChengeUserInfoView.as_view(), 
		name = 'profile_change'),
	path('accounts/profile/change/<int:pk>', profile_bb_change, 
									name = 'profile_bb_change'),
	path('accounts/profile/delete/<int:pk>', profile_bb_delete,
									name = 'profile_bb_delete'),
	path('accounts/profile/add/', profile_bb_add,
									name = 'profile_bb_add'),
	path('accounts/profile/<int:pk>', profile_bb_detail, 
										name = 'profile_bb_detail'),
	path('accounts/profile/', profile, name = 'profile'),
	path('accounts/logout/', BBLogoutView.as_view(), name = 'logout'),
	path('<int:rubric_pk>/<int:pk>/', detail, name = 'detail'),
	path('<int:pk>/', by_rubric, name='by_rubric'),
	path('accounts/login/', BBLoginView.as_view(), name = 'login'),
	path('<str:page>/', other_page, name = 'other'),
	path('', index, name='index'),
]

bboard/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from captcha.fields import CaptchaField

from .models import AdvUser
from .models import user_registrated
from .models import SuperRubric, SubRubric
from .models import Bb, AdditionalImage
from .models import Comment

class UserCommentForm(forms.ModelForm):#форма для добавления комментариев авторизованого пользователя
	class Meta:
		model = Comment
		exclude = ('is_active',)#указывет что поле 'is_active' не нужно включать в форму
		widgets = {'bb': forms.HiddenInput}#скрыли ключ объявления

class GuestCommentForm(forms.ModelForm):#форма для добавления комментариев неавторизованого пользователя
	captcha = CaptchaField(label='Введите текст с картинки',
				error_messages = {'invalid':'Неправильный текст'})
	class Meta:
		model = Comment
		exclude = ('is_active',)
		widgets = {'bb': forms.HiddenInput}

class BbForm(forms.ModelForm):
	class Meta:
		model = Bb
		fields = '__all__'
		widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields = '__all__')

class SearchForm(forms.Form):
	keyword = forms.CharField(required= False, max_length=20, label='')

class SubRubricForm(forms.ModelForm):
	super_rubric = forms.ModelChoiceField(
					queryset = SuperRubric.objects.all(), empty_label=None,
					label='Надрубрики', required=True)

	class Meta:
		model = SubRubric
		fields = '__all__'

class RegisterUserForm(forms.ModelForm):
	email = forms.EmailField(required=True,
							label='Адрес электронной почты')
	password1 = forms.CharField(label = 'Пароль', 
		widget=forms.PasswordInput,
		help_text = password_validation.password_validators_help_text_html())
	password2 = forms.CharField(label = 'Пароль (повторно)',
		widget = forms.PasswordInput,
		help_text = 'Введите пароль ещё раз для проверки')

	def clean_password(self): #- проверяем пароль на корректность
		password1=self.cleaned_data['password1']
		if password1:
			password_validation.validate_password(password1)
		return password1

	def clean(self): #- проверяем совпадают ли пароли
		super().clean()
		password1=self.cleaned_data['password1']#получаем данные через объект cleaned_data
		password2=self.cleaned_data['password2']#получаем данные через объект cleaned_data
		if password1 and password2 and password1 != password2:
			errors = {'password2': ValidationError(
				'Введенные пароли не совпадают', code = 'password_mismatch')}
			raise ValidationError(errors)

	def save(self, commit=True): #-сохраняем пользователя
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1']) # устанавливаем пороль пользователя
		user.is_active = False #при создание нового пользователя он не активен
		user.is_activated = False #при создание нового пользователя он не прошёл активацию
		if commit:
			user.save()
		user_registrated.send(RegisterUserForm, instance=user)#если такой аргумент указан(instance), то save() обновит переданную модель
		return user

	class Meta:
		model = AdvUser
		fields = ('username', 'email','password1', 'password2',
		 		'first_name', 'last_name', 'send_messages')

class ChengeUserInfoForm(forms.ModelForm):
	email = forms.EmailField(required=True,#обязательно к заполнению
							label='Адрес электронной почты')

	class Meta:
		model = AdvUser
		fields = ('username', 'email', 'first_name', 'last_name',
					'send_messages')

bboard/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template 
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import PasswordChangeView
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect

from .models import AdvUser
from .forms import ChengeUserInfoForm
from .forms import RegisterUserForm
from .utilities import signer
from .models import SubRubric, Bb
from .forms import SearchForm
from .forms import BbForm, AIFormSet
from .forms import UserCommentForm, GuestCommentForm
from .models import Comment


#страница исправления объявлений
@login_required
def profile_bb_change(request, pk):
	bb = get_object_or_404(Bb, pk=pk)
	if request.method == 'POST':
		form = BbForm(request.POST, request.FILES, instance=bb)
		if form.is_valid():
			bb = form.save()
			formset = AIFormSet(request.POST, request.FILES, instance=bb)
			if formset.is_valid():
				formset.save()
				messages.add_message(request, messages.SUCCESS,
									'Объявление исправлено')
				return redirect('bboard:profile')
	else:
		form = BbForm(instance=bb)
		formset = AIFormSet(instance=bb)
		context = {'form': form, 'formset':formset}
		return render(request, 'bboard/profile_bb_change.html', context)

#страница удаления объявлений
@login_required
def profile_bb_delete(request, pk):
	bb = get_object_or_404(Bb, pk=pk)
	if request.method == 'POST':
		bb.delete()
		messages.add_message(request, messages.SUCCESS, 
							'Объявление удалено')
		return redirect('bboard:profile')
	else:
		context = {'bb':bb }
		return render(request, 'bboard/profile_bb_delete.html', context)

#страница добавления объявлений
@login_required
def profile_bb_add(request):
	if request.method == 'POST':
		form = BbForm(request.POST, request.FILES)
		if form.is_valid():
			bb = form.save()
			formset = AIFormSet(request.POST, request.FILES, instance = bb)#связывает добавленные изображения с объявлением
			if formset.is_valid():
				formset.save()
				messages.add_message(request, messages.SUCCESS,
									'Объявление добавлено')
				return redirect('bboard:profile')
	else:
		form = BbForm(initial = {'author':request.user.pk})#связываем добавленное объявление с пользователем
		formset = AIFormSet()
	context = {'form':form, 'formset': formset}
	return render(request, 'bboard/profile_bb_add.html', context)

#страница добавленных пользователем объявлений
@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais, }
    return render(request, 'bboard/profile_bb_detail.html', context)

#страница деталей объявления
def detail(request, rubric_pk, pk):
	bb = get_object_or_404(Bb, pk=pk)#выводим модель Bb или ошибку 404
	ais = bb.additionalimage_set.all()#берём все дополнительные изображения
	comments = Comment.objects.filter(bb=pk, is_active=True)#только те что активны
	initial = {'bb':bb.pk}# в поле bb заносим ключ объявление на котором сейчас находимся
	if request.user.is_authenticated:#если пользователь зарегестрирован
		initial['author'] = request.user.username #занозим его имя в поле author
		form_class = UserCommentForm #используем форму для авторизованых пользователей
	else:
		form_class = GuestCommentForm #в любом другом случае используем форму для гостя
	form = form_class(initial=initial)# при выводе нового комментария будет выводить пустую форму
	if request.method == 'POST':
		c_form = form_class(request.POST)
		if c_form.is_valid():
			c_form.save()#если комментарий успешно добавлен то выводится пустая форма из переменной form
			messages.add_message(request, messages.SUCCESS,
									'Комментарий добавлен')
		else:
			form = c_form#если нет то выводится комментариий и указываются ошибки из-зи которых он не выведен
			messages.add_message(request, messages.WARNING,
								'Комментарий не добавлен')
	context = {'bb':bb, 'ais':ais, 'comments':comments, 'form':form }
	return render(request, 'bboard/detail.html', context)

#страница списка обявлений и поиска
def by_rubric(request, pk):
	rubric = get_object_or_404(SubRubric, pk=pk)#выводим подрубрику выбранную пользователем
	bbs = Bb.objects.filter(is_active = True, rubric=pk) #выводим те объявления которые активны
	if 'keyword' in request.GET: #если в поле поиска что-то введено то
		keyword = request.GET['keyword']#получаем это слово
		q = Q(title__icontains=keyword) | Q(content__icontains=keyword) #проверяет в СУБД есть ключевое слово в название или описании(без учёта регистра)
		bbs = bbs.filter(q)#применяем фильтрацию к объявлениям
	else:
		keyword = ''
	form = SearchForm(initial={'keyword': keyword})#кючевое слово выводится вместе с фомрой
	paginator = Paginator(bbs, 2)
	if 'page' in request.GET:
		page_num = request.GET['page']
	else:
		page_num = 1 
	page = paginator.get_page(page_num)
	context = {'rubric':rubric, 'page':page, 'bbs':page.object_list,
				'form':form}
	return render(request, 'bboard/by_rubric.html', context)


#страница удаления пользователя
class DeleteUserView(LoginRequiredMixin, DeleteView):
	model = AdvUser
	template_name = 'bboard/delete_user.html'
	success_url = reverse_lazy('bboard:index')

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk #-извлекаем и сохраняем ключ пользователя
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		logout(request)
		messages.add_message(request, messages.SUCCESS,
										'Пользователь удалён')
		return super().post(request, *args, **kwargs)

	def get_object(self, queryset=None): #-извлекаем исправляемую запись
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)

#Страница активации пользователя
def user_activate(request, sign):
	try:
		username = signer.unsign(sign)#цифровая подпись
	except BadSignature:
		return render(request, 'bboard/bad_signature.html') #Активация пользователя с таким именем прошла неудачно
	user = get_object_or_404(AdvUser, username=username)
	if user.is_activated: #Активация пользователя с таким именем был активирован ранее
		template = 'bboard/user_is_activated.html'
	else: #Пользователь с таким именем успешно активирован
		template = 'bboard/activation_done.html'
		user.is_active = True #пользователь активен
		user.is_activated = True #пользователь активирован
		user.save()
	return render(request, template)

#Страница об успешной регистрации ользователя
class RegisterDoneView(TemplateView):
	template_name = 'bboard/register_done'

#Страница регистрации пользователя
class RegisterUserView(CreateView):
	model = AdvUser
	template_name = 'bboard/register_user.html'
	form_class = RegisterUserForm
	success_url = reverse_lazy('bboard:register_done')

#Страница смены пароля
class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin,
												PasswordChangeView):
	template_name = 'bboard/password_change.html'
	success_url = reverse_lazy('bboard:profile')
	success_message = 'Пароль пользователя изменён' #всплывающее сообщение

#Страница с изменение личных данных пользователя
class ChengeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,
											UpdateView):
	model = AdvUser # используемая модель
	template_name = 'bboard/change_user_info.html' # используемый шаблон
	form_class = ChengeUserInfoForm # используемая форма
	success_url = reverse_lazy('bboard:profile') #страница, которая используется в случае успешного проведения операции
	#reverse_lazt - Эта функция может быть полезна в случае, если вам нужно вернуть URL-адрес прежде, чем ваши настройки URLConf будут загружены.
	success_message = 'Личные данные пользователя изменены' #всплывающее сообщение

	def dispatch(self, request, *args, **kwargs):
		self.user_id = request.user.pk #-извлекаем и сохраняем ключ пользователя
		return super().dispatch(request, *args, **kwargs) #super()-возможность использования в классе потомке, методов класса-родителя.

	def get_object(self, queryset=None): #-извлекаем исправляемую запись
		if not queryset:
			queryset = self.get_queryset()
		return get_object_or_404(queryset, pk=self.user_id)

#Страница профиля
@login_required
def profile(request):
	bbs = Bb.objects.filter(author=request.user.pk)
	context = {'bbs': bbs}
	return render(request, 'bboard/profile.html', context)

#Страница выхода
class BBLogoutView(LogoutView):
	template_name = 'bboard/logout.html'

#Страница авторизации
class BBLoginView(LoginView):
	template_name = 'bboard/login.html'

# Дополнительные страницы
def other_page(request, page):
	try:
		template = get_template('bboard/' + page + '.html')
	except TemplateDoesNotExist: 
		raise Http404
		#не удалось загрузить шаблон
	return HttpResponse(template.render(request=request))

# Главная страница
def index(request):
	bbs = Bb.objects.filter(is_active=True)[:10]
	context = {'bbs':bbs }
	return render(request, 'bboard/index.html', context)

bboard/templates/bboard/about.html
{% extends "layout/basic.html"%}

{% block title %} О сайте {% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</p>
{% endblock %}

bboard/templates/bboard/activation_done.html
{% extends "layout/basic.html"%}

{% block title %} Активация выполнена {% endblock %}

{% block content %}
<h2> Активация </h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'bboard:login '%}">Войти на сайт</a></p>
{% endblock %} 

bboard/templates/bboard/bad_signature.html
{% extends "layout/basic.html"%}

{% block title %} Ошибка при активации {% endblock %}

{% block content %}
<h2> Активация </h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'bboard:register '%}">Зарегистрироваться 
повторно</a></p>
{% endblock %} 

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html"%}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %} {{rubric}} {% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
	<div class="row">
		<div class="col">&nbsp;</div>
		<form class="col-md-auto form-inline">
			{% bootstrap_form form show_label=False %}
			{% bootstrap_button content='Искать' button_type='submit' %}
		</form>
	</div>
</div>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
	<li class="media my-5 p-3 border">
		{% url 'bboard:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
		<a href="{{ url }}{{ all }}">
		{% if bb.image %}
		<img class="mr-3" src="{% thumbnail bb.image 'default' %}">
		{% else %}
		<img class="mr-3" src="{% static 'bboard/empty.jpg'%}">
		{% endif %}
		</a>
		<div class="media-body">
			<h3><a href="{{ url }}{{ all }}">
			{{ bb.title }}</a></h3>
			<div>{{ bb.content }}</div>
			<p class="text-right font-weight-bold">{{ bb.price }}руб.</p>
			<p class="text-right font-italic">{{ bb.created_at }}</p>
		</div>
	</li>
	{% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

bboard/templates/bboard/delete_user.html
{% extends "layout/basic.html"%}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя {{object.username}}</h2>
<form method="post">
	{% csrf_token %}
	{% buttons submit='Удалить' %} {% endbuttons %}
</form>
{% endblock %}

bboard/templates/bboard/detail.html
{% extends "layout/basic.html"%}

{% load bootstrap4 %}

{% block title %} {{bb.title}} - {{bb.rubric.name}} {% endblock %}

{% block content %}
<div class="container-fluid mt-3">
	<div class="row">
		{% if bb.image %}
		<div class="col-md-auto"><img src="{{ bb.image.url }}"
			class="main-image"></div>
		{% endif %}
		<div class="col">
			<h2>{{ bb.title }}</h2>
			<p>{{ bb.content }}</p>
			<p class="font-weight-bold">{{ bb.price }}руб.</p>
			<p>{{ bb.contacts }}</p>
			<p class="text-right font-italic">Объявление добавлено
			{{ bb.created_at }}</p>
		</div>
	</div>
</div>
{% if ais %}
    <div class="d-flex justify-content-between flex-wrap mt-5">
    	{% for ai in ais%}
    	<div>
    		<img class="additional-image" src="{{ ai.image.url }}">
    	</div>
    	{% endfor %}
    </div>
{% endif %}
<p><a href="{% url 'bboard:by_rubric' pk=bb.rubric.pk %}{{all}}">
	Назад</a></p>
<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal'%}
	{% buttons submit='Добавить'%}{% endbuttons %}
</form>
{% if comments %}
<div class="mt-5">
	{% for comment in comments %}
	<div class="my-2 p-2 border">
		<h5>{{ comment.author }}</h5>
		<p>{{ comment.content }}</p>
		<p class="text-right font-italic">{{ comment.created_at }}</p>
	</div>
	{% endfor %}
</div>
{% endif %}
{% endblock %}

bboard/templates/bboard/login.html
{% extends "layout/basic.html"%}

{% load bootstrap4 %}

{% block title %} Вход {% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
	{% csrf_token %}
	<a href="{% url 'social:begin' 'vk-oauth2' %}">
	Войти через ВКонтакте</a>
	{% bootstrap_form form layout='horisontal' %}
	<input type="hidden" name="next" value="{{next}}">
	{% buttons submit='Войти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %} 

bboard/templates/bboard/logout.html
{% extends "layout/basic.html"%}

{% block title %} Выход {% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно выйшли из профиля.</p>
{% endblock %}

bboard/templates/bboard/password_change.html
{% extends "layout/basic.html"%}

{% load bootstrap4 %}

{% block title %} Смена пароля {% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horisontal' %}
	<input type="hidden" name="next" value="{{next}}">
	{% buttons submit='Сменить пароль' %} {% endbuttons %}
</form>
{% endblock %}

bboard/templates/bboard/profile.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'bboard:profile_bb_add' %}">Добавить объявление</a></p>
{% if bbs %}
<h3>Ваши объявления</h3>
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'bboard:profile_bb_detail' pk=bb.pk as url %}
        <a href="{{ url }}">
        {% if bb.image %}
        <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'bboard/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
            <p>Рубрика: {{ bb.rubric }}</p>
            <h3><a href="{{ url }}">{{ bb.title }}</a></h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
            <p class="text-right mt-2">
                <a href="{% url 'bboard:profile_bb_change' pk=bb.pk %}">Исправить</a>
                <a href="{% url 'bboard:profile_bb_delete' pk=bb.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

bboard/templates/bboard/profile_bb_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title%}Доска объявлений -
Профидь пользователя{% endblock %}

{% block content %}
<h2>Добавление объявлений</h2>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal'%}
	{% bootstrap_formset formset layout='horizontal' %}
	{% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

bboard/templates/bboard/profile_bb_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2>Правка объявления</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

bboard/templates/bboard/register_done.html
{% extends "layout/basic.html"%}

{% block title %} Регистрация завершена {% endblock %}

{% block content %}
<h2>Регистрация </h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо
для активации.</p>
{% endblock %} 

bboard/templates/bboard/user_is_activated.html
{% extends "layout/basic.html"%}

{% block title %} Пользователь уже активирован {% endblock %}

{% block content %}
<h2> Активация </h2>
<p>Активация пользователя с таким именем был активирован ранее.</p>
<p><a href="{% url 'bboard:login '%}">Войти на сайт</a></p>
{% endblock %} 